# Generated by Django 2.2.3 on 2019-08-01 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item.Categories'),
            preserve_default=False,
        ),
    ]
